KonradIT/goprowifihack

URL-Style.mkdn

HTTP response codes added from what I saw (Hero 3 Black and Silver editions)

added HTTP response codes

---

HERO4.md

Hey! I've checked these commands with my GoPro HERO4 Black v03.00 and came up with the update.
Still working on the Secondary commands because neither of those works for me.

GoPro Hero4 Black v03.00

---

HERO4/HERO4-RES.FPS- table.md

Need to still format and change filename

Create HERO4-RES.FPS- table.md

---

HERO3/Framerates-Resolutions.md

* GoPro Camera(s):  ALL HERO3 and HERO3+ Cameras 
* Tested on: N/A
* Firmware version: HD3 Firmware

Framerates-Resolutions.md

---

HERO3/WifiCommands.md

* GoPro Camera(s): Hero3+ Black / Hero3 
* Tested on: June 22, 2016
* Firmware version: HD3.11.0303  / HD3.09.03.03

Add command to delete a specific file.

---

HERO4/CameraStatus.md
HERO4/WifiCommands.md

* GoPro Camera(s): HERO4 Silver
* Tested on: HERO4 Silver, 2016-07-03
* Firmware version: HD4.01.03.00.00

Updated CameraStatus.md and WifiCommands.md

---

HERO4/WifiCommands.md

* GoPro Camera(s): HERO4 Silver
* Tested on: HERO4 Silver, 2016-07-03
* Firmware version: HD4.01.03.00.00
fixed nightlapse and timelapse intervals
more stuff you might want to test @silent3rror

fixed timelapse and nightlapse intervals

---

HERO4/CameraStatus.md
HERO4/WifiCommands.md

* GoPro Camera(s): HERO4 Silver
* Tested on: HERO4 Silver, 2016-07-03
* Firmware version: HD4.01.03.00.00

Added LCD Brightness and LCD Lock

---

HERO4/HERO4-Session.md

* GoPro Camera(s): HERO4 Silver
* Tested on: HERO4 Silver, 2016-07-03
* Firmware version: HD4.01.03.00.00

added name of status:31 value

---

HERO4/WifiCommands.md

* GoPro Camera(s): Hero 4
* Tested on: Hero 4 Black
* Firmware version: v05.00

missing gp/gpControl in URL

---

HERO5/gpControl-HERO5Session.json

* GoPro Camera(s): Hero 5 Session
* Tested on: N/A
* Firmware version: HD5.03.01.57.00
There is not currently a JSON dump from a Hero 5 Session. This PR adds that file at `HERO5/gpControl-HERO5Session.json`.

Added Hero 5 Session gpControl JSON

---

HERO4/CameraStatus.md

* GoPro Camera(s): Hero 4
* Tested on: Hero 4 Black
* Firmware version: 5.00

54 in status is free space on memory card

---

HERO4/WifiCommands.md

Not sure if this fits into the structure but this is anyway a little messed up ?!?
* GoPro Camera(s): HERO4 Black
* Tested on: HERO4 Black
* Firmware version: 5.00

added set date_time

---

HERO/WifiCommands.md
HERO4/WifiCommands.md

Small typo

---

Bluetooth/Platforms/RaspberryPi.md
Bluetooth/README.md

It's time to rename the repo! 🎉
Just a first draft, but it should work. Looking forward to hear some feedback.
I plan to add more, hopefully more Bluetooth commands and a tutorial for Mac.
Anyway problem with GoPro's WiFi falling asleep seems to be solved!

Add controlling over Bluetooth Low Energy

---

Libraries.md

* GoPro Camera(s): HERO5
* Tested on: HERO5
* Firmware version:

Added GoLang link

---

HERO7/HERO7-Commands.md

* GoPro Camera(s): Hero7
* Tested on: Hero7
* Firmware version: N/A
Corrected commands works as expected (previous version returned 400)

Corrected superview command

---

HERO7/Mediabrowsing.md

When using media list command, + guess at some meanings
* GoPro Camera(s): 7 black
* Tested on: 7 black
* Firmware version: 01.90

Added extra fields received using hero7 black

---

Bluetooth/README.md

Just a minor update to documentation,

Add Arch Linux to platforms in README.md

---

Libraries.md

if you want we can add the lib to your list

added arduino lib

---

HERO3/WifiCommands.md

* GoPro Camera(s): HERO3
* Tested on: HERO3
* Firmware version: 02.39

Fix Leds command

---

Libraries.md

* GoPro Camera(s): HERo5
* Tested on: HERO5 Session
* Firmware version: HD5.03.02.51.00

Add reference to Rust-API

---

README.md

Redirectiong Hero8 webcam users to the right page.

Hero8 uses Hero9 commands for Webcam
